// lib/nutrition-db.ts

export const NUTRITION_DATABASE = {
  proteins: [
    { name: "Poulet (Blanc)", density: "22g pour 100g (Cuit)", visual: "1 filet standard (~120g) = 26g de prot" },
    { name: "Dinde (Escalope)", density: "24g pour 100g (Cuit)", visual: "1 belle escalope (~150g) = 36g de prot" },
    { name: "Boeuf haché (5% MG)", density: "21g pour 100g (Cuit)", visual: "1 steak haché standard = 21g de prot" },
    { name: "Steak de boeuf (Faux-filet)", density: "25g pour 100g (Cuit)", visual: "1 portion (~150g) = 37g de prot" },
    { name: "Oeuf entier", density: "6g par oeuf", visual: "3 oeufs = 18g de prot" },
    { name: "Blanc d'oeuf", density: "11g pour 100g", visual: "Le blanc de 3 oeufs = 10g de prot" },
    { name: "Saumon (Frais)", density: "20g pour 100g (Cuit)", visual: "1 pavé standard (~120g) = 24g de prot" },
    { name: "Thon (En boîte au naturel)", density: "25g pour 100g", visual: "1 petite boîte égouttée (~140g) = 35g de prot" },
    { name: "Cabillaud / Poisson blanc", density: "18g pour 100g (Cuit)", visual: "1 filet (~150g) = 27g de prot" },
    { name: "Crevettes (Décortiquées)", density: "20g pour 100g", visual: "1 grosse poignée (~100g) = 20g de prot" },
    { name: "Jambon blanc (Dégraissé)", density: "18g pour 100g", visual: "2 tranches = 14g de prot" },
    { name: "Tofu ferme", density: "15g pour 100g", visual: "1/2 bloc (~100g) = 15g de prot" },
    { name: "Tempeh", density: "19g pour 100g", visual: "1 portion (~100g) = 19g de prot" },
    { name: "Seitan", density: "25g pour 100g", visual: "1 portion (~100g) = 25g de prot" },
    { name: "Lentilles (Cuites)", density: "9g pour 100g", visual: "4 Cuillères à Soupe (C.à.S) = 9g de prot" },
    { name: "Fromage blanc 0%", density: "8g pour 100g", visual: "1 gros bol (200g) = 16g de prot" },
    { name: "Skyr", density: "10g pour 100g", visual: "1 pot individuel (140g) = 14g de prot" },
    { name: "Yaourt Grec", density: "10g pour 100g", visual: "1 gros bol (200g) = 20g de prot" },
    { name: "Whey Protéine (Poudre)", density: "80g pour 100g", visual: "1 dosette (scoop de 30g) = ~24g de prot" },
    { name: "Lait demi-écrémé", density: "3.3g pour 100ml", visual: "1 grand verre (250ml) = 8g de prot" }
  ],
  carbs: [
    { name: "Riz basmati (Cuit)", density: "28g pour 100g", visual: "3 grosses Cuillères à Soupe (C.à.S) = ~30g de glucides" },
    { name: "Riz complet (Cuit)", density: "25g pour 100g", visual: "3 grosses C.à.S = ~25g de glucides" },
    { name: "Pâtes classiques (Cuites)", density: "30g pour 100g", visual: "1 assiette creuse normale = ~60g de glucides" },
    { name: "Pâtes complètes (Cuites)", density: "27g pour 100g", visual: "1 assiette creuse normale = ~55g de glucides" },
    { name: "Pomme de terre (Cuite)", density: "17g pour 100g", visual: "2 pommes de terre moyennes = ~35g de glucides" },
    { name: "Patate douce (Cuite)", density: "20g pour 100g", visual: "1 patate douce moyenne = ~40g de glucides" },
    { name: "Flocons d'avoine (Crus)", density: "60g pour 100g", visual: "5 C.à.S bombées = ~30g de glucides" },
    { name: "Quinoa (Cuit)", density: "21g pour 100g", visual: "3 grosses C.à.S = ~21g de glucides" },
    { name: "Semoule / Couscous (Cuit)", density: "23g pour 100g", visual: "3 grosses C.à.S = ~23g de glucides" },
    { name: "Blé / Ebly (Cuit)", density: "27g pour 100g", visual: "3 grosses C.à.S = ~27g de glucides" },
    { name: "Pois chiches (Cuits)", density: "20g pour 100g", visual: "4 C.à.S = ~20g de glucides" },
    { name: "Haricots rouges (Cuits)", density: "20g pour 100g", visual: "4 C.à.S = ~20g de glucides" },
    { name: "Pain de mie complet", density: "40g pour 100g", visual: "2 tranches = ~28g de glucides" },
    { name: "Pain baguette traditionnel", density: "50g pour 100g", visual: "1/4 de baguette = ~30g de glucides" },
    { name: "Banane", density: "23g pour 100g", visual: "1 banane moyenne = ~25g de glucides" },
    { name: "Pomme", density: "14g pour 100g", visual: "1 pomme moyenne = ~20g de glucides" },
    { name: "Galettes de riz", density: "80g pour 100g", visual: "3 galettes = ~20g de glucides" },
    { name: "Miel", density: "82g pour 100g", visual: "1 C.à.S = ~17g de glucides rapides" },
    { name: "Sirop d'érable", density: "67g pour 100g", visual: "1 C.à.S = ~13g de glucides rapides" },
    { name: "Muesli (Sans sucre ajouté)", density: "60g pour 100g", visual: "4 C.à.S bombées = ~30g de glucides" }
  ],
  fats: [
    { name: "Huile d'olive", density: "10g pour 1 C.à.S", visual: "1 C.à.S = 10g de lipides purs" },
    { name: "Huile de colza", density: "10g pour 1 C.à.S", visual: "1 C.à.S = 10g de lipides (Riche en Oméga-3)" },
    { name: "Huile de coco", density: "10g pour 1 C.à.S", visual: "1 C.à.S = 10g de lipides saturés" },
    { name: "Beurre doux", density: "8g pour 10g", visual: "1 noisette de beurre = 8g de lipides" },
    { name: "Beurre de cacahuète", density: "8g pour 1 C.à.S", visual: "1 C.à.S rase = 8g de lipides" },
    { name: "Beurre d'amande", density: "8g pour 1 C.à.S", visual: "1 C.à.S rase = 8g de lipides" },
    { name: "Amandes (Entières)", density: "50g pour 100g", visual: "1 petite poignée fermée (~30g) = 15g de lipides" },
    { name: "Noix (Cerneaux)", density: "65g pour 100g", visual: "1 petite poignée = 19g de lipides" },
    { name: "Noix de cajou", density: "45g pour 100g", visual: "1 petite poignée = 13g de lipides" },
    { name: "Noisettes", density: "60g pour 100g", visual: "1 petite poignée = 18g de lipides" },
    { name: "Noix de macadamia", density: "75g pour 100g", visual: "1 petite poignée = 22g de lipides" },
    { name: "Avocat", density: "15g pour 1/2 avocat", visual: "Moitié d'un avocat = 15g de lipides" },
    { name: "Chocolat noir (85%+)", density: "45g pour 100g", visual: "2 gros carrés (~20g) = 9g de lipides" },
    { name: "Graines de chia", density: "30g pour 100g", visual: "1 C.à.S = 4.5g de lipides" },
    { name: "Graines de lin (Moulues)", density: "40g pour 100g", visual: "1 C.à.S = 6g de lipides" },
    { name: "Graines de courge", density: "49g pour 100g", visual: "1 petite poignée = 15g de lipides" },
    { name: "Olives noires", density: "15g pour 100g", visual: "10 olives = ~5g de lipides" },
    { name: "Fromage à pâte dure (Comté, Parmesan)", density: "30g pour 100g", visual: "1 portion (30g) = 9g de lipides" },
    { name: "Crème fraîche (30% MG)", density: "30g pour 100g", visual: "1 C.à.S bombée = 6g de lipides" },
    { name: "Pesto", density: "45g pour 100g", visual: "1 C.à.S = 7g de lipides" }
  ]
};